//created on: 14-Apr-2019
package thesistimetableplanning.solver;
	dialect "java"

//list any import classes here.
import org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScoreHolder;
import thesistimetableplanning.domain.Defense;
import thesistimetableplanning.domain.Timeslot;



global HardSoftScoreHolder scoreHolder;

rule "Defense timeslots grouped by common session and have no holes between them"
	when
		$timeslot1 : Timeslot($timeslotId1 : id,
							$session1 : session)
		$timeslot2 : Timeslot($timeslotId2 : id,
					id > $timeslotId1,
					session == $session1)
		$defense1 : Defense($defenseId1 : id,
					timeslot != $timeslot1)
		$defense2 : Defense(id != $defenseId1,
					timeslot == $timeslot2)
	then
		scoreHolder.penalize(kcontext);
		//scoreHolder.addSoftConstraintMatch(kcontext, -1);
end

rule "Commission member does not swap with a new member in the same session"
	when
		$defense1 : Defense(timeslot != null,
					$id1 : id)
		$defense2 : Defense(timeslot != null,
					!hasSameCommiteeOnSameSession($defense1),
					id != $id1)
	then
		scoreHolder.penalize(kcontext);
		//scoreHolder.addSoftConstraintMatch(kcontext, -1);
end

rule "Defense timeslot only for single author"
	when
		$defense1 : Defense(timeslot != null,
					$timeslot : timeslot,
					$id1 : id)
		$defense2 : Defense(timeslot != null,
					overlapsTimeslot($defense1),
					$timeslot == timeslot,
					$id1 != id)
	then
		scoreHolder.penalize(kcontext);
		//scoreHolder.addHardConstraintMatch(kcontext, -1);
//		$defense1.addNotUniqueTimeslotConstraint($timeslot, $defense1, $defense2);
//		$defense2.addNotUniqueTimeslotConstraint($timeslot, $defense1, $defense2);
end

rule "Defense not on authors unavailable timeslot"
	when
		$defense : Defense(isAuthorsUnavailableTimeslot(),
					$timeslot : timeslot,
					timeslot != null)
	then
		scoreHolder.penalize(kcontext);
		//scoreHolder.addHardConstraintMatch(kcontext, -1);
		$defense.addAuthorUnavailableConstraint($timeslot);
end

rule "Defense not on authors unavailable timeslot tag"
	when
		$defense : Defense(isAuthorsUnavailableTimeslotTag(),
					$timeslot : timeslot,
					timeslot != null)
	then
		scoreHolder.penalize(kcontext);
		//scoreHolder.addHardConstraintMatch(kcontext, -1);
		$defense.addAuthorUnavailableTagConstraint($timeslot);
end

rule "Defense not on commission members unavailable timeslot"
	when
		$defense : Defense($count : isCommissionMembersUnavailableTimeslot() > 0,
							$timeslot : timeslot,
							timeslot != null)
	then
		scoreHolder.penalize(kcontext, $count);
	//	scoreHolder.addHardConstraintMatch(kcontext, $count * -1);
		$defense.addCommissionUnavailableConstraint($timeslot);
end

rule "Defense not on commission members unavailable timeslot tag"
	when
		$defense : Defense($count : isCommissionMembersUnavailableTimeslotTag() > 0,
							$timeslot : timeslot,
							timeslot != null)
	then
		scoreHolder.penalize(kcontext, $count);
	//	scoreHolder.addHardConstraintMatch(kcontext, $count * -1);
		$defense.addCommissionUnavailableTagConstraint($timeslot);
end

rule "Defense not on authors not preferred timeslot"
	when
		$defense : Defense(isAuthorsNotPreferredTimeslot(),
					$timeslot : timeslot,
					timeslot != null)
	then
		scoreHolder.penalize(kcontext);
		//scoreHolder.addSoftConstraintMatch(kcontext, -1);
		$defense.addAuthorNotPreferredConstraint($timeslot);
end

rule "Defense not on authors not preferred timeslot tag"
	when
		$defense : Defense(isAuthorsNotPreferredTimeslotTag(),
					$timeslot : timeslot,
					timeslot != null)
	then
		scoreHolder.penalize(kcontext);
		//scoreHolder.addSoftConstraintMatch(kcontext, -1);
		$defense.addAuthorNotPreferredTagConstraint($timeslot);
end

rule "Defense on authors preferred timeslot"
	when
		$defense : Defense(isAuthorsPreferredTimeslot(),
					$timeslot : timeslot,
					timeslot != null)
	then
		scoreHolder.reward(kcontext);
		//scoreHolder.addSoftConstraintMatch(kcontext, 1);
		$defense.addAuthorPreferredConstraint($timeslot);
end

rule "Defense on authors preferred timeslot tag"
	when
		$defense : Defense(isAuthorsPreferredTimeslotTag(),
					$timeslot : timeslot,
					timeslot != null)
	then
		scoreHolder.reward(kcontext);
		//scoreHolder.addSoftConstraintMatch(kcontext, 1);
		$defense.addAuthorPreferredTagConstraint($timeslot);
end

rule "Defense not on authors supervisors not preferred timeslot"
	when
		$defense : Defense($count : isAuthorsSupervisorsNotPreferredTimeslot() > 0,
							$timeslot : timeslot,
							timeslot != null)
	then
		scoreHolder.penalize(kcontext, $count);
		//scoreHolder.addSoftConstraintMatch(kcontext, $count * -1);
		$defense.addSupervisorNotPreferredConstraint($timeslot);
end

rule "Defense not on authors supervisors not preferred timeslot tag"
	when
		$defense : Defense($count : isAuthorsSupervisorsNotPreferredTimeslotTag() > 0,
							$timeslot : timeslot,
							timeslot != null)
	then
		scoreHolder.penalize(kcontext, $count);
		//scoreHolder.addSoftConstraintMatch(kcontext, $count * -1);
		$defense.addSupervisorNotPreferredTagConstraint($timeslot);
end

rule "Defense on authors supervisors preferred timeslot"
	when
		$defense : Defense($count : isAuthorsSupervisorsPreferredTimeslot() > 0,
							$timeslot : timeslot,
							timeslot != null)
	then
		scoreHolder.reward(kcontext, $count);
		//scoreHolder.addSoftConstraintMatch(kcontext, $count);
		$defense.addSupervisorPreferredConstraint($timeslot);
end

rule "Defense on authors supervisors preferred timeslot tag"
	when
		$defense : Defense($count : isAuthorsSupervisorsPreferredTimeslotTag() > 0,
							$timeslot : timeslot,
							timeslot != null)
	then
		scoreHolder.reward(kcontext, $count);
		//scoreHolder.addSoftConstraintMatch(kcontext, $count);
		$defense.addSupervisorPreferredTagConstraint($timeslot);
end

rule "Defense not on authors supervisors unavailable timeslot"
	when
		$defense : Defense($count : isAuthorsSupervisorsUnavailableTimeslot() > 0,
							$timeslot : timeslot,
							timeslot != null)
	then
		scoreHolder.penalize(kcontext, $count);
		//scoreHolder.addSoftConstraintMatch(kcontext, $count * -1);
		$defense.addSupervisorUnavailableConstraint($timeslot);
end

rule "Defense not on authors supervisors unavailable timeslot tag"
	when
		$defense : Defense($count : isAuthorsSupervisorsUnavailableTimeslotTag() > 0,
							$timeslot : timeslot,
							timeslot != null)
	then
		scoreHolder.penalize(kcontext, $count);
		//scoreHolder.addSoftConstraintMatch(kcontext, $count * -1);
		$defense.addSupervisorUnavailableTagConstraint($timeslot);
end

rule "Defense not on commission members not preferred timeslot"
	when
		$defense : Defense($count : isCommissionMembersNotPreferredTimeslot() > 0,
							$timeslot : timeslot,
							timeslot != null)
	then
		scoreHolder.penalize(kcontext, $count);
		//scoreHolder.addSoftConstraintMatch(kcontext, $count * -1);
		$defense.addCommissionNotPreferredConstraint($timeslot);
end

rule "Defense not on commission members not preferred timeslot tag"
	when
		$defense : Defense($count : isCommissionMembersNotPreferredTimeslotTag() > 0,
							$timeslot : timeslot,
							timeslot != null)
	then
		scoreHolder.penalize(kcontext, $count);
		//scoreHolder.addSoftConstraintMatch(kcontext, $count * -1);
		$defense.addCommissionNotPreferredTagConstraint($timeslot);
end

rule "Defense on commission members preferred timeslot"
	when
		$defense : Defense($count : isCommissionMembersPreferredTimeslot() > 0,
							$timeslot : timeslot,
							timeslot != null)
	then
		scoreHolder.reward(kcontext, $count);
		//scoreHolder.addSoftConstraintMatch(kcontext, $count);
		$defense.addCommissionPreferredConstraint($timeslot);
end

rule "Defense on commission members preferred timeslot tag"
	when
		$defense : Defense($count : isCommissionMembersPreferredTimeslotTag() > 0,
							$timeslot : timeslot,
							timeslot != null)
	then
		scoreHolder.reward(kcontext, $count);
		//scoreHolder.addSoftConstraintMatch(kcontext, $count);
		$defense.addCommissionPreferredTagConstraint($timeslot);
end

rule "Defense authors grouped by common supervisor"
    when
        $defense1 : Defense(timeslot != null,
        				$defenseId1 : id)
        $defense2 : Defense(timeslot != null,
       					hasSameSupervisorOnSameSession($defense1),
        				id != $defenseId1)
    then
		scoreHolder.reward(kcontext);
        //scoreHolder.addSoftConstraintMatch(kcontext, 1);
end